# more details here : https://singularityhub.github.io/singularity-compose/#/?id=quick-start
# specs here : https://singularityhub.github.io/singularity-compose/#/spec/spec-2.0
version: '2.0'
instances:
  zookeeper:
    image: docker://wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: docker://wurstmeister/kafka
    container_name: Kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
