dist: Focal

language: python
python:
  - "3.8"
  
# command to install dependencies
before_install:
  - sudo apt-get -y install libgdal-dev libgdal1h python3-gdal graphviz redis-server libopencv-contrib-dev


install:
  - pip install -r install/requirements.txt
script:
  - pytest test_framework.py
