dist: Focal

language: python
python:
  - "3.8"
  
# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install -y wget python3-pytest
  - wget https://github.com/apptainer/apptainer/releases/download/v1.1.3/apptainer_1.1.3_amd64.deb
  - sudo apt-get install -y ./apptainer_1.1.3_amd64.deb
  - sudo apptainer build tf2_addons.sif install/tf2_addons.def
  
script:
  - apptainer exec tf2_addons.sif pytest test_framework.py
