name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8.10' 
      - name: Install dependencies
        run: |
          pip install --upgrade pip==20.2.4
          pip install -r requirements.txt;
          pip install sphinx furo sphinx_click sphinx-copybutton
          pip install sphinx-toolbox
      - name: Sphinx build
        run: |
          sphinx-build docsrc/source/ docs/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/
          force_orphan: true
